<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-16T16:20:17 IST" name="Suite" finished-at="2024-11-16T16:20:55 IST" duration-ms="37515">
    <groups>
    </groups>
    <test started-at="2024-11-16T16:20:17 IST" name="Test" finished-at="2024-11-16T16:20:55 IST" duration-ms="37515">
      <class name="SOR_testcases.SOR_LoginTestCase">
        <test-method is-config="true" signature="Initalization()[pri:0, instance:SOR_testcases.SOR_LoginTestCase@660acfb]" started-at="2024-11-16T16:20:17 IST" name="Initalization" finished-at="2024-11-16T16:20:21 IST" duration-ms="3934" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initalization -->
        <test-method signature="Check_InValid_User_Name()[pri:1, instance:SOR_testcases.SOR_LoginTestCase@660acfb]" started-at="2024-11-16T16:20:21 IST" name="Check_InValid_User_Name" finished-at="2024-11-16T16:20:24 IST" duration-ms="3216" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Check_InValid_User_Name -->
        <test-method signature="Check_Blank_Username()[pri:2, instance:SOR_testcases.SOR_LoginTestCase@660acfb]" started-at="2024-11-16T16:20:24 IST" name="Check_Blank_Username" finished-at="2024-11-16T16:20:27 IST" duration-ms="2410" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Check_Blank_Username -->
        <test-method signature="Check_Blank_Password()[pri:3, instance:SOR_testcases.SOR_LoginTestCase@660acfb]" started-at="2024-11-16T16:20:27 IST" name="Check_Blank_Password" finished-at="2024-11-16T16:20:29 IST" duration-ms="2486" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Check_Blank_Password -->
        <test-method signature="Check_InValid_Password()[pri:4, instance:SOR_testcases.SOR_LoginTestCase@660acfb]" started-at="2024-11-16T16:20:29 IST" name="Check_InValid_Password" finished-at="2024-11-16T16:20:32 IST" duration-ms="2679" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Check_InValid_Password -->
        <test-method signature="Check_Valid_Credentials()[pri:5, instance:SOR_testcases.SOR_LoginTestCase@660acfb]" started-at="2024-11-16T16:20:32 IST" name="Check_Valid_Credentials" finished-at="2024-11-16T16:20:54 IST" duration-ms="21661" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed: LeftMenu is not displayed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed: LeftMenu is not displayed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at SOR_Pages.SOR_Login_Page.Check_Valid_Credentials(SOR_Login_Page.java:79)
at SOR_testcases.SOR_LoginTestCase.Check_Valid_Credentials(SOR_LoginTestCase.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Check_Valid_Credentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SOR_testcases.SOR_LoginTestCase@660acfb]" started-at="2024-11-16T16:20:54 IST" name="tearDown" finished-at="2024-11-16T16:20:55 IST" duration-ms="338" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- SOR_testcases.SOR_LoginTestCase -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
