<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MIIPL_ON_Rajendra_Mane" failures="0" tests="1" name="SOR_testcases.SOR_Alert_Configuration_TestCase" time="0.025" errors="1" timestamp="2025-02-15T15:44:03 IST" skipped="0">
  <testcase classname="SOR_testcases.SOR_Alert_Configuration_TestCase" name="Create_Role" time="0.025">
    <error message="Cannot invoke &quot;org.apache.poi.xwpf.usermodel.XWPFDocument.createParagraph()&quot; because &quot;SOR_resources.Utility$TextFileLogger.document&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.xwpf.usermodel.XWPFDocument.createParagraph()" because "SOR_resources.Utility$TextFileLogger.document" is null
at SOR_resources.Utility$TextFileLogger.logMessage(Utility.java:790)
at SOR_Pages.SOR_Login_Page.Check_Valid_Credentials(SOR_Login_Page.java:56)
at SOR_testcases.SOR_Alert_Configuration_TestCase.Create_Role(SOR_Alert_Configuration_TestCase.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- Create_Role -->
  <system-out/>
</testsuite> <!-- SOR_testcases.SOR_Alert_Configuration_TestCase -->
